### ISSUE TITLE
RN Screens Patch 

### ISSUE THREAD

**Issue by mikevocalz** [react-native-tvos/TVReanimated#1]
The Patch for RN Screens is failing. My current version is:     "react-native-screens": "^3.10.2",

**Comment by douglowder** [comment]
I'll take a quick look, can you use version 3.4.0 in the meantime?

**Comment by douglowder** [comment]
I pushed a commit that fixes it. Looks like you can remove the patch for RNScreens if you are using 3.10.2.

**Comment by mikevocalz** [comment]
i just tried this and im now getting the error:   Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager. I think @react-navigation/material-top-tabs installs this as a needed dependency @douglowder

**Comment by douglowder** [comment]
Is this happening on Android or tvOS?

**Comment by mikevocalz** [comment]
> 

TVOS and on android im getting the old error prior to the patches
<img width="1255" alt="Screen Shot 2022-01-26 at 1 42 30 PM" src="https://user-images.githubusercontent.com/7896619/151226527-39138a8c-bf0b-43cd-af25-23d9338629b6.png">


@douglowder

**Comment by douglowder** [comment]
I'm not seeing this issue.  Be sure to do

```sh
cd TVReanimated
rm -r node_modules ios/Pods ios/Podfile.lock
yarn
cd ios
pod install
open TVReanimated.xcworkspace
```
Kill any running packagers. Then build and run the TV target.

**Comment by mikevocalz** [comment]
is there any way possible this can work with updated patches/dependency versions and the new 68.2-2 release?

**Comment by douglowder** [comment]
@mikevocalz :  Yes it can. See for example the dependencies in https://github.com/douglowder/TVInputDemo .

I'll spend some time this week updating this repo for 68.2-2.

**Comment by douglowder** [comment]
Actually the update went pretty quick, give it a try 😃

**Comment by mikevocalz** [comment]
Thanks so much. it actually works great on androidtv but doesnt load on tvOS
