### ISSUE TITLE
reanimated-2.9.1 required for android and 0.69.5

### ISSUE THREAD

**Issue by ashnfb** [react-native-tvos/TVReanimated#3]
Hello Doug, I don't see an issue template, so please let me know if you would prefer a better format?

With the latest react-native-tvos 0.69.5-x, I've noticed that Apple TV will only build with react-native-reanimated 2.8.0 or lower.  But Android will only run with react-native-reanimated 2.9.1 and higher.

When setting react-native-reanimated to 2.9.1 in the example, the app shows a RCT fatal crash, with a very generic "UNSUPPORTED".

I've spent a few days on this, and have not been able to understand where that UNSUPPORTED error is coming from. Would you have any ideas on debugging that?

thank you
Ash

**Comment by douglowder** [comment]
It is happening because of a crash very early in the Reanimated setup. The real cause seems to be that somehow Reanimated thinks it should be running with Hermes, and Hermes does not exist on tvOS yet. (I'm working on that now.)

I seem to recall that I got Android working with 2.8.0, but I'll check again.

I'll have another look and update the repo with my best recommendations for using RNTV 0.69.5-x.

**Comment by ashnfb** [comment]
Thank you for the reply Doug, that helps; I will try and see if I can solve that problem here with a patch

**Comment by douglowder** [comment]
The issues with simultaneously fixing tvOS and Android in 0.69 seem to be complex. I'll come back to this after some other TV work is complete (Hermes on tvOS, 0.70 migration).

**Comment by bohlec** [comment]
hi @douglowder - is there an update to this issue? I need to figure out a solution. Thanks!

**Comment by douglowder** [comment]
No update yet... Once we finish work on 0.71 for TV (which will include Hermes for tvOS) we will come back to this issue.

FYI @yusufyildirim

**Comment by bohlec** [comment]
@douglowder - I suspect this new MR might solve this issue. At the very least, it fixes the code that is causing the `Unsupported` error mentioned by the OP.

https://github.com/react-native-tvos/react-native-tvos/pull/446

**Comment by douglowder** [comment]
The fix looks good! I added others to the review. Assuming no issues with the fix, we will get this merged and released in 0.69.6-2

**Comment by douglowder** [comment]
Merged a PR that brings in the fix as a patch -- closing.

**Comment by ashnfb** [comment]
Thank you to all involved in fixing this!
